title: Architectuur
lang: en
description: Architectuur kaders en richtlijnen

remote_theme: rundocs/jekyll-rtd-theme

readme_index:
  with_frontmatter: true

exclude:
  - Makefile
  - Gemfile
  - Gemfile.lock

plugins:
  - jemoji
  - jekyll-avatar
  - jekyll-mentions
  
  relative_links:
    enabled: true
    collections: true
 
  
