title: Architectuur Repository
lang: nl
description: Architectuur, kaders en richtlijnen, best-practices
github_username: Fred125

remote_theme: rundocs/jekyll-rtd-theme

# Set this to true to get LaTeX math equation support
# use_math:

readme_index:
  with_frontmatter: true
  
relative_links:
    enabled: true
    collections: true

exclude:
  - Makefile
  - Gemfile
  - Gemfile.lock

plugins:
  - jemoji
  - jekyll-avatar
  - jekyll-mentions

 
  
